### PR TITLE
Upgrade elixir

### PR DESCRIPTION
**Pull request by bautrey37**
EN-5855

### CODE REVIEW

**Comment by indrekj** [comment]
I took over this PR because I want to add tracing support and that needs Elixir v1.11.

**Comment by bautrey37** [comment]
> I took over this PR because I want to add tracing support and that needs Elixir v1.11.

Awesome! This would also resolve this issue. https://glia.atlassian.net/browse/EN-5855.

**Review by riiwo — APPROVED** [review]

**Comment by bautrey37** [comment]
Code looks good! 
There are some warnings in the [CI](https://github.com/salemove/task_bunny/actions/runs/1439941465) about some deprecated functions. It looks likes at least some are coming from the old poison library. Can you consider if its possible to upgrade this as well?

**Comment by indrekj** [comment]
> It looks likes some are coming from the old poison/coveralls library. Can you consider if its possible to upgrade this as well?

Poison already is upgraded. These are from dependency compilations so that's not that important. The `mix test` itself is clean of errors.

**Pull request merged**
