### PR TITLE
Grab ownership of task-bunny for Quantum

### PR DESCRIPTION
**Pull request by sturmer**
See
https://salemove.slack.com/archives/CBJJE330U/p1734003443555299?thread_ts=1733918079.450199&cid=CBJJE330U for context.

### CODE REVIEW

**Comment by bautrey37** [comment]
If this owner is being assigned, because I contributed to this in 2021, then that doesn't make sense that Quantum is the owner. Back then, I was in Engage team, which then split into Messenger team. This is the original issue for my [change](https://glia.atlassian.net/jira/software/c/projects/QVA/issues/EN-5832?jql=project%20IN%20(QVA,%20EN)%20AND%20(textfields%20~%20%22EN-5832%22%20OR%20issuekey%20%3D%20%22EN-5832%22)%20ORDER%20BY%20created%20DESC) . 

Quantum team does use some RabbitMQ functionality, but I believe most of this is from Engagement-registry.

**Comment by sturmer** [comment]
> If this owner is being assigned, because I contributed to this in 2021, then that doesn't make sense that Quantum is the owner. Back then, I was in Engage team, which then split into Messenger team. This is the original issue for my [change](https://glia.atlassian.net/jira/software/c/projects/QVA/issues/EN-5832?jql=project%20IN%20(QVA,%20EN)%20AND%20(textfields%20~%20%22EN-5832%22%20OR%20issuekey%20%3D%20%22EN-5832%22)%20ORDER%20BY%20created%20DESC) .
> 
> Quantum team does use some RabbitMQ functionality, but I believe most of this is from Engagement-registry.

I don't know the criteria Anna used to propose this assignment, but it doesn't make sense to assign this to _any_ team. I'm taking it just because this is not supposed to receive any change, and somebody needs to take it anyway, and personally I don't see why not us. I've added Mikk in the PR because if he wants to fight for this, he can. I don't mind either way.

**Review by anna-agafonova — APPROVED** [review]

**Comment by sturmer** [comment]
!squash

**Comment by sturmer** [comment]
!merge

**Comment by sturmer** [comment]
!merge

**Pull request merged**
